name = "MLDs"
uuid = "cac4bed1-6c8c-4dbe-be0d-c63a427c1233"
authors = ["Tommaso Stentella <stentell@molgen.mpg.de> and contributors"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.10"
