name = "MLDs"
uuid = "cac4bed1-6c8c-4dbe-be0d-c63a427c1233"
version = "0.1.4"
authors = ["Tommaso Stentella <stentell@molgen.mpg.de> and contributors"]

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
FastGaussQuadrature = "1.1.0"
ForwardDiff = "1"
julia = "1.10"
